/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.THCSDataAnalyserRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.THCSEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.THCSDataAnalyserOrganization;
import Business.TreatmentTypes.TreatmentTypeDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
/**
 *
 * @author Gaya 3
 */
public class CreateReportsDashboardJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private EcoSystem business;
    private THCSDataAnalyserOrganization daOrganization;
    private THCSEnterprise thcsEnterprise; 
    private Network network;

    /**
     * Creates new form DataCollectorWorkAreaJPanel
     */
    public CreateReportsDashboardJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business, Enterprise enterprise, Network network) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.daOrganization = (THCSDataAnalyserOrganization)organization;
        this.thcsEnterprise = (THCSEnterprise)enterprise;
        this.network = network;
        populateTreatmentTypesComboBox();

        
    }
    
    private void populateTreatmentTypesComboBox(){
        ArrayList<String> treatmentTypeDirectory;
        TreatmentTypeDirectory tt = new TreatmentTypeDirectory();
        treatmentTypeDirectory = tt.getTreatmentTypes();
        treatmentTypeDirectory.forEach((treatType) -> {
            treatmentTypesComboBox.addItem(treatType);
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackJButton = new javax.swing.JButton();
        compareHospitalsBtn = new javax.swing.JButton();
        treatmentTypesComboBox = new javax.swing.JComboBox<>();
        imageLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        compareNetworksBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 204));

        BackJButton.setBackground(new java.awt.Color(255, 255, 255));
        BackJButton.setText("<< Data Analysis Dashboard");
        BackJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackJButtonActionPerformed(evt);
            }
        });

        compareHospitalsBtn.setBackground(new java.awt.Color(255, 255, 255));
        compareHospitalsBtn.setText("Compare Hospitals");
        compareHospitalsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compareHospitalsBtnActionPerformed(evt);
            }
        });

        imageLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        imageLabel.setForeground(new java.awt.Color(255, 102, 0));
        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Generate Reports");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setText("Select Treatment Type");

        compareNetworksBtn.setBackground(new java.awt.Color(255, 255, 255));
        compareNetworksBtn.setText("Compare Networks");
        compareNetworksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compareNetworksBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(compareHospitalsBtn)
                        .addGap(53, 53, 53)
                        .addComponent(compareNetworksBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(63, 63, 63)
                            .addComponent(BackJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(114, 114, 114)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(105, 105, 105)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addComponent(treatmentTypesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BackJButton)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(treatmentTypesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(compareHospitalsBtn)
                            .addComponent(compareNetworksBtn))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackJButtonActionPerformed
                                           
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackJButtonActionPerformed

    private void compareHospitalsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compareHospitalsBtnActionPerformed
        
        String treatment_type = (String)treatmentTypesComboBox.getSelectedItem();
        HealthCostLineChart healthCostLineChart = new HealthCostLineChart();

        healthCostLineChart.launchChart(business, thcsEnterprise, network, treatment_type, "hospitals");

    }//GEN-LAST:event_compareHospitalsBtnActionPerformed

    private void compareNetworksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compareNetworksBtnActionPerformed
        String treatment_type = (String)treatmentTypesComboBox.getSelectedItem();
        HealthCostLineChart healthCostLineChart = new HealthCostLineChart();

        healthCostLineChart.launchChart(business, thcsEnterprise, network, treatment_type, "networks");
    }//GEN-LAST:event_compareNetworksBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackJButton;
    private javax.swing.JButton compareHospitalsBtn;
    private javax.swing.JButton compareNetworksBtn;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> treatmentTypesComboBox;
    // End of variables declaration//GEN-END:variables
}
