/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.THCSDataAnalyserRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.THCSEnterprise;
import Business.Hospitals.HospitalDirectory;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.THCSDataAnalyserOrganization;
import Business.Organization.THCSDataCollectorOrganization;
import Business.TreatmentTypes.TreatmentTypeDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import userinterface.THCSDataCollectorRole.DataCollectorWorkAreaJPanel;

/**
 *
 * @author Gaya 3
 */
public class DataAnalysisDashboardJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private THCSDataAnalyserOrganization daOrganization;
    private THCSEnterprise thcsEnterprise; 
    private Network network;
    

    /**
     * Creates new form DataCollectorWorkAreaJPanel
     */
    public DataAnalysisDashboardJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business, Enterprise enterprise, Network network) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.daOrganization = (THCSDataAnalyserOrganization)organization;
        this.thcsEnterprise = (THCSEnterprise)enterprise;
        this.network = network;
       
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackJButton = new javax.swing.JButton();
        viewReportsBtn = new javax.swing.JButton();
        createReportsBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 204));

        BackJButton.setBackground(new java.awt.Color(255, 255, 255));
        BackJButton.setText("<< My Work Area");
        BackJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackJButtonActionPerformed(evt);
            }
        });

        viewReportsBtn.setBackground(new java.awt.Color(255, 255, 255));
        viewReportsBtn.setText("View Reports >>");
        viewReportsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReportsBtnActionPerformed(evt);
            }
        });

        createReportsBtn.setBackground(new java.awt.Color(255, 255, 255));
        createReportsBtn.setText("Generate Reports >>");
        createReportsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createReportsBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Data Analysis Dashboard");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(BackJButton)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewReportsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createReportsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BackJButton)
                    .addComponent(jLabel2))
                .addGap(102, 102, 102)
                .addComponent(createReportsBtn)
                .addGap(26, 26, 26)
                .addComponent(viewReportsBtn)
                .addContainerGap(229, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackJButtonActionPerformed
                                           
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DataAnalyserWorkAreaJPanel pwajp = (DataAnalyserWorkAreaJPanel) component;
        pwajp.populateWorkQueueTable();
        pwajp.populateHistoryTable();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackJButtonActionPerformed

    private void createReportsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createReportsBtnActionPerformed
        CreateReportsDashboardJPanel createReportsDashboardJPanel = new CreateReportsDashboardJPanel(userProcessContainer, userAccount, daOrganization, business, thcsEnterprise, network);
        userProcessContainer.add("createReportsDashboardJPanel", createReportsDashboardJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createReportsBtnActionPerformed

    private void viewReportsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReportsBtnActionPerformed
        ViewReportsDashboardJPanel viewReportsDashboardJPanel = new ViewReportsDashboardJPanel(userProcessContainer, userAccount);
        userProcessContainer.add("viewReportsDashboardJPanel", viewReportsDashboardJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewReportsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackJButton;
    private javax.swing.JButton createReportsBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton viewReportsBtn;
    // End of variables declaration//GEN-END:variables
}
