/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.THCSManagerRole;

import Business.TreatmentTypes.TreatmentTypeDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Gaya 3
 */
public class ReportsDashboardJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    

    /**
     * Creates new form DataCollectorWorkAreaJPanel
     */
    public ReportsDashboardJPanel(JPanel userProcessContainer, UserAccount account) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        populateTreatmentTypesComboBox();

        
    }
    
    private void populateTreatmentTypesComboBox(){
        ArrayList<String> treatmentTypeDirectory;
        TreatmentTypeDirectory tt = new TreatmentTypeDirectory();
        treatmentTypeDirectory = tt.getTreatmentTypes();
        treatmentTypeDirectory.forEach((treatType) -> {
            treatmentTypesComboBox.addItem(treatType);
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackJButton = new javax.swing.JButton();
        viewHospitalReportBtn = new javax.swing.JButton();
        treatmentTypesComboBox = new javax.swing.JComboBox<>();
        imageLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        viewNetworkReportbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 204));

        BackJButton.setBackground(new java.awt.Color(255, 255, 255));
        BackJButton.setText("<< My Work Area");
        BackJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackJButtonActionPerformed(evt);
            }
        });

        viewHospitalReportBtn.setBackground(new java.awt.Color(255, 255, 255));
        viewHospitalReportBtn.setText("View Hospitlas Reports");
        viewHospitalReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewHospitalReportBtnActionPerformed(evt);
            }
        });

        imageLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        imageLabel.setForeground(new java.awt.Color(255, 102, 0));
        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("View Reports");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setText("Select Treatment Type");

        viewNetworkReportbtn.setBackground(new java.awt.Color(255, 255, 255));
        viewNetworkReportbtn.setText("View Networks Reports");
        viewNetworkReportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewNetworkReportbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(treatmentTypesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(viewHospitalReportBtn)
                                .addGap(30, 30, 30)
                                .addComponent(viewNetworkReportbtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BackJButton)
                                .addGap(172, 172, 172)
                                .addComponent(jLabel2)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(BackJButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(treatmentTypesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewHospitalReportBtn)
                    .addComponent(jLabel1)
                    .addComponent(viewNetworkReportbtn))
                .addGap(19, 19, 19)
                .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackJButtonActionPerformed
                                           
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManagerWorkAreaJPanel pwajp = (ManagerWorkAreaJPanel) component;
        pwajp.populateGovtRequestTable();
        pwajp.populateRequestTable();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackJButtonActionPerformed

    private void viewHospitalReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewHospitalReportBtnActionPerformed
        
        String treatment_type = (String)treatmentTypesComboBox.getSelectedItem();
        String imagePath = "snapshotsHospitals/" + treatment_type + ".png";
        imageLabel.setIcon(null);
        BufferedImage myPicture = null;
        try {
            myPicture = ImageIO.read(new File(imagePath));
            if(myPicture != null){
                imageLabel.setIcon(new ImageIcon(myPicture));
                imageLabel.revalidate();
                imageLabel.repaint();
                imageLabel.update(imageLabel.getGraphics());
            }else{
                imageLabel.setIcon(null);
                imageLabel.setText("No Report Available");
            }
            
        } catch (IOException ex) {
            imageLabel.setIcon(null);
            imageLabel.setText("No Report Available");
            
            System.out.println(ex);
        }

    }//GEN-LAST:event_viewHospitalReportBtnActionPerformed

    private void viewNetworkReportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewNetworkReportbtnActionPerformed
        String treatment_type = (String)treatmentTypesComboBox.getSelectedItem();
        String imagePath = "snapshotsNetworks/" + treatment_type + ".png";
        imageLabel.setIcon(null);
        BufferedImage myPicture = null;
        try {
            myPicture = ImageIO.read(new File(imagePath));
            if(myPicture != null){
                imageLabel.setIcon(new ImageIcon(myPicture));
                imageLabel.revalidate();
                imageLabel.repaint();
                imageLabel.update(imageLabel.getGraphics());
            }else{
                imageLabel.setIcon(null);
                imageLabel.setText("No Report Available");
            }
            
        } catch (IOException ex) {
            imageLabel.setIcon(null);
            imageLabel.setText("No Report Available");
            
            System.out.println(ex);
        }
    }//GEN-LAST:event_viewNetworkReportbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackJButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> treatmentTypesComboBox;
    private javax.swing.JButton viewHospitalReportBtn;
    private javax.swing.JButton viewNetworkReportbtn;
    // End of variables declaration//GEN-END:variables
}
