/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.THCSDataCollectorRole;

import Business.Enterprise.THCSEnterprise;
import Business.HealthCost.HealthCost;
import Business.Network.Network;
import Business.WorkQueue.HospitalInfoWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author mahitha
 */
public class UpdateHealthCostRecordJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    HospitalInfoWorkRequest request;
    private THCSEnterprise thcsEnterprise; 
    private Network network;
    private HealthCost healthCost;
    
     private boolean consultationError = false;
    private boolean byPassSurgeryError = false;
    private boolean angioSugeryError = false;
    private boolean kneeSurgeryError = false;
    private boolean corneaSugeryError = false;
    private boolean mriScanError = false;
    private boolean eegError = false;
    private boolean ecgError = false;
    private boolean xrayError = false;
    private boolean fluVaccineError = false;
    private boolean hepAVaccineError = false;
    private boolean hepBVaccineError = false;
    private boolean hpvVaccineError = false;
    private boolean ipvVaccineError = false;
    private boolean mmRVaccineError = false;


    /**
     * Creates new form InfoProcessWorkRequestJPanel
     */
    public UpdateHealthCostRecordJPanel(JPanel userProcessContainer, Network network, HealthCost healthCost) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.healthCost = healthCost;
        
        LocationNameLabel.setText(network.getName());
        
        fillForm();
    }
    
    private void fillForm(){
        hospitalNameLabel.setText(healthCost.getHospitalName());
        
        txtFieldConsultationFee.setText(Double.toString(this.healthCost.getConsultationFee()));
        txtFieldMRIcost.setText(Double.toString(this.healthCost.getMriCost()));
        txtFieldEEGcost.setText(Double.toString(this.healthCost.getEegCost()));
        txtFieldECGcost.setText(Double.toString(this.healthCost.getEcgCost()));
        txtFieldXRaycost.setText(Double.toString(this.healthCost.getxRayCost()));
        txtFieldHrtSurgery.setText(Double.toString(this.healthCost.getHeartBypassSurgery()));
        txtFieldAngSurgery.setText(Double.toString(this.healthCost.getAngioplastySurgery()));
        txtFieldKRsurgery.setText(Double.toString(this.healthCost.getKneeReplacementSurgery()));
        txtFieldCorneaSurgery.setText(Double.toString(this.healthCost.getCorneaSurgery()));
        txtFieldFluVaccine.setText(Double.toString(this.healthCost.getFluVaccine()));
        txtFieldHptAVaccine.setText(Double.toString(this.healthCost.getHepatitisAVaccine()));
        txtFieldHptBVaccine.setText(Double.toString(this.healthCost.getHepatitisBVaccine()));
        txtFieldHPV.setText(Double.toString(this.healthCost.getHPVvaccine()));
        txtFieldIPV.setText(Double.toString(this.healthCost.getIPVvaccine()));
        txtFieldMMR.setText(Double.toString(this.healthCost.getMMRVaccine()));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFieldConsultationFee = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        LocationNameLabel = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        hospitalNameLabel = new javax.swing.JLabel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txtFieldMMR = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtFieldIPV = new javax.swing.JTextField();
        txtFieldHptAVaccine = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtFieldFluVaccine = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtFieldHPV = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtFieldHptBVaccine = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        fluErrorLabel4 = new javax.swing.JLabel();
        hepBErrorLabel4 = new javax.swing.JLabel();
        hepAErrorLabel4 = new javax.swing.JLabel();
        hpvErrorLAbel4 = new javax.swing.JLabel();
        ipvErrorLabel4 = new javax.swing.JLabel();
        mmrErrorLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        txtFieldHrtSurgery = new javax.swing.JTextField();
        heartErrorLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtFieldAngSurgery = new javax.swing.JTextField();
        angioErrorLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtFieldKRsurgery = new javax.swing.JTextField();
        kneeErrorLAbel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtFieldCorneaSurgery = new javax.swing.JTextField();
        corneaErrorLabel = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtFieldMRIcost = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFieldEEGcost = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFieldECGcost = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFieldXRaycost = new javax.swing.JTextField();
        MRIErrorLabel = new javax.swing.JLabel();
        EEGErrorLabel = new javax.swing.JLabel();
        ECGErrorLabel = new javax.swing.JLabel();
        xrayErrorLabel = new javax.swing.JLabel();
        consultationErrorLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 204));

        backJButton.setBackground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<< Health Costs Directory");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Hospital Name:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Consultation Fee:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtFieldConsultationFee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldConsultationFeeFocusLost(evt);
            }
        });

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Location :");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Update Health Cost");
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtFieldMMR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldMMRFocusLost(evt);
            }
        });

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("MMR Vaccine:");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtFieldIPV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldIPVFocusLost(evt);
            }
        });

        txtFieldHptAVaccine.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldHptAVaccineFocusLost(evt);
            }
        });

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Hepatitis A Vaccine:");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtFieldFluVaccine.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldFluVaccineFocusLost(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Flu Vaccine:");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("IPV Vaccine:");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtFieldHPV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldHPVFocusLost(evt);
            }
        });

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("HPV Vaccine:");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtFieldHptBVaccine.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldHptBVaccineFocusLost(evt);
            }
        });

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Hepatitis B Vaccine:");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        fluErrorLabel4.setForeground(new java.awt.Color(204, 0, 51));
        fluErrorLabel4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fluErrorLabel4FocusLost(evt);
            }
        });

        hepBErrorLabel4.setForeground(new java.awt.Color(204, 0, 51));

        hepAErrorLabel4.setForeground(new java.awt.Color(204, 0, 51));

        hpvErrorLAbel4.setForeground(new java.awt.Color(204, 0, 51));

        ipvErrorLabel4.setForeground(new java.awt.Color(204, 0, 51));

        mmrErrorLabel4.setForeground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtFieldMMR, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFieldIPV, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFieldHPV, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFieldHptBVaccine, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFieldHptAVaccine, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFieldFluVaccine, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fluErrorLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hepBErrorLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hepAErrorLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hpvErrorLAbel4, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ipvErrorLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mmrErrorLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFieldFluVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addComponent(fluErrorLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(txtFieldHptAVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hepAErrorLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFieldHptBVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addComponent(hepBErrorLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFieldHPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16))
                    .addComponent(hpvErrorLAbel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(txtFieldIPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ipvErrorLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(txtFieldMMR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mmrErrorLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane5.addTab("Vaccines", jPanel1);

        txtFieldHrtSurgery.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldHrtSurgeryFocusLost(evt);
            }
        });
        txtFieldHrtSurgery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldHrtSurgeryActionPerformed(evt);
            }
        });

        heartErrorLabel.setForeground(new java.awt.Color(204, 0, 51));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Heart Bypass Surgery:");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Angioplasty Surgery:");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtFieldAngSurgery.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldAngSurgeryFocusLost(evt);
            }
        });

        angioErrorLabel.setForeground(new java.awt.Color(204, 0, 51));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Knee Replacement Surgery:");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtFieldKRsurgery.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldKRsurgeryFocusLost(evt);
            }
        });

        kneeErrorLAbel.setForeground(new java.awt.Color(204, 0, 51));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Cornea Surgery:");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtFieldCorneaSurgery.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldCorneaSurgeryFocusLost(evt);
            }
        });
        txtFieldCorneaSurgery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldCorneaSurgeryActionPerformed(evt);
            }
        });

        corneaErrorLabel.setForeground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFieldKRsurgery, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtFieldCorneaSurgery, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtFieldAngSurgery, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtFieldHrtSurgery, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(heartErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(angioErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kneeErrorLAbel, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(corneaErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtFieldHrtSurgery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(heartErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel10)
                                            .addComponent(txtFieldAngSurgery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(angioErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFieldKRsurgery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))
                            .addComponent(kneeErrorLAbel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(txtFieldCorneaSurgery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(corneaErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Surgery", jPanel7);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("MRI cost:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtFieldMRIcost.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldMRIcostFocusLost(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("EEG cost:");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtFieldEEGcost.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldEEGcostFocusLost(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("ECG cost:");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtFieldECGcost.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldECGcostFocusLost(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("X-Ray cost:");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtFieldXRaycost.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldXRaycostFocusLost(evt);
            }
        });
        txtFieldXRaycost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldXRaycostActionPerformed(evt);
            }
        });

        MRIErrorLabel.setForeground(new java.awt.Color(204, 0, 51));

        EEGErrorLabel.setForeground(new java.awt.Color(204, 0, 51));

        ECGErrorLabel.setForeground(new java.awt.Color(204, 0, 51));

        xrayErrorLabel.setForeground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFieldEEGcost, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(txtFieldMRIcost, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFieldECGcost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFieldXRaycost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(49, 49, 49)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MRIErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EEGErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ECGErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xrayErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtFieldMRIcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MRIErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtFieldEEGcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(EEGErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldECGcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ECGErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtFieldXRaycost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(xrayErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 783, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane5.addTab("Scans", jPanel8);

        consultationErrorLabel.setForeground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LocationNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hospitalNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFieldConsultationFee, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(consultationErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(backJButton)
                        .addGap(205, 205, 205)
                        .addComponent(jLabel20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(438, 438, 438)
                        .addComponent(updateBtn)))
                .addContainerGap(747, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(jLabel20))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LocationNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hospitalNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtFieldConsultationFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(consultationErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateBtn)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        HealthCostsDirectoryJPanel pwajp = (HealthCostsDirectoryJPanel) component;
        pwajp.populateTable();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
      
        if(txtFieldConsultationFee.getText().isEmpty() || txtFieldMRIcost.getText().isEmpty() || txtFieldEEGcost.getText().isEmpty() || txtFieldECGcost.getText().isEmpty()
                || txtFieldXRaycost.getText().isEmpty() || txtFieldHrtSurgery.getText().isEmpty() || 
                txtFieldAngSurgery.getText().isEmpty() || txtFieldKRsurgery.getText().isEmpty()
                    || txtFieldCorneaSurgery.getText().isEmpty() || txtFieldFluVaccine.getText().isEmpty() || txtFieldHptAVaccine.getText().isEmpty() || 
                txtFieldHptBVaccine.getText().isEmpty() || txtFieldHPV.getText().isEmpty() || txtFieldIPV.getText().isEmpty() || 
                txtFieldMMR.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill all the costs");
            return;
        }
           
        if(consultationError || byPassSurgeryError || angioSugeryError || kneeSurgeryError
                || corneaSugeryError || mriScanError || eegError || ecgError || xrayError
                    || fluVaccineError || hepAVaccineError || hepBVaccineError || hpvVaccineError || ipvVaccineError || mmRVaccineError){
            JOptionPane.showMessageDialog(null, "Please fill all the costs within specified range");
            return;
        }
        
        this.healthCost.setConsultationFee(Double.parseDouble(txtFieldConsultationFee.getText()));
        this.healthCost.setMriCost(Double.parseDouble(txtFieldMRIcost.getText()));
        this.healthCost.setxRayCost(Double.parseDouble(txtFieldXRaycost.getText()));
        this.healthCost.setEcgCost(Double.parseDouble(txtFieldECGcost.getText()));
        this.healthCost.setEegCost(Double.parseDouble(txtFieldEEGcost.getText()));
        
        this.healthCost.setFluVaccine(Double.parseDouble(txtFieldFluVaccine.getText()));
        this.healthCost.setHPVvaccine(Double.parseDouble(txtFieldHPV.getText()));
        this.healthCost.setIPVvaccine(Double.parseDouble(txtFieldIPV.getText()));
        this.healthCost.setHepatitisAVaccine(Double.parseDouble(txtFieldHptAVaccine.getText()));
        this.healthCost.setHepatitisBVaccine(Double.parseDouble(txtFieldHptBVaccine.getText()));
        this.healthCost.setMMRVaccine(Double.parseDouble(txtFieldMMR.getText()));

        
        this.healthCost.setHeartBypassSurgery(Double.parseDouble(txtFieldHrtSurgery.getText()));
        this.healthCost.setCorneaSurgery(Double.parseDouble(txtFieldCorneaSurgery.getText()));
        this.healthCost.setAngioplastySurgery(Double.parseDouble(txtFieldAngSurgery.getText()));
        this.healthCost.setKneeReplacementSurgery(Double.parseDouble(txtFieldKRsurgery.getText()));
        
        
        JOptionPane.showMessageDialog(null, "Health cost info successfully updated");
    }//GEN-LAST:event_updateBtnActionPerformed

    private void txtFieldHrtSurgeryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldHrtSurgeryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldHrtSurgeryActionPerformed

    private void txtFieldXRaycostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldXRaycostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldXRaycostActionPerformed

    private void fluErrorLabel4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fluErrorLabel4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_fluErrorLabel4FocusLost

    private void txtFieldFluVaccineFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldFluVaccineFocusLost
        // TODO add your handling code here:
        if(txtFieldFluVaccine.getText().isEmpty()){
            fluVaccineError = true;
        }
        else{
            double cost;
            try{
                cost = Double.parseDouble(txtFieldFluVaccine.getText());
            }catch(NumberFormatException e){
                fluVaccineError = true;
                JOptionPane.showMessageDialog(null, "Please enter a valid float value for cost");
                return;
            }
            if (cost < 20){
                fluVaccineError = true;
            }else{
                fluVaccineError = false;
            }
        }
        
        
        if(fluVaccineError){
            fluErrorLabel4.setText("Flu vaccine cost must be greater than 20$");
        }else{
            fluErrorLabel4.setText("");
        }
    }//GEN-LAST:event_txtFieldFluVaccineFocusLost

    private void txtFieldHptAVaccineFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldHptAVaccineFocusLost
        // TODO add your handling code here:
        if(txtFieldHptAVaccine.getText().isEmpty()){
            hepAVaccineError = true;
        }
        else{
            double cost;
            try{
                cost = Double.parseDouble(txtFieldHptAVaccine.getText());
            }catch(NumberFormatException e){
                hepAVaccineError = true;
                JOptionPane.showMessageDialog(null, "Please enter a valid float value for cost");
                return;
            }
            if (cost < 20){
                hepAVaccineError = true;
            }else{
                hepAVaccineError = false;
            }
        }
        
        
        if(hepAVaccineError){
            hepAErrorLabel4.setText("Hepatities A Vaccine cost must be greater than 20$");
        }else{
            hepAErrorLabel4.setText("");
        }
    }//GEN-LAST:event_txtFieldHptAVaccineFocusLost

    private void txtFieldHptBVaccineFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldHptBVaccineFocusLost
        // TODO add your handling code here:
        if(txtFieldHptBVaccine.getText().isEmpty()){
            hepBVaccineError = true;
        }
        else{
            double cost;
            try{
                cost = Double.parseDouble(txtFieldHptBVaccine.getText());
            }catch(NumberFormatException e){
                hepBVaccineError = true;
                JOptionPane.showMessageDialog(null, "Please enter a valid float value for cost");
                return;
            }
            if (cost < 20){
                hepBVaccineError = true;
            }else{
                hepBVaccineError = false;
            }
        }
        
        
        if(hepBVaccineError){
            hepBErrorLabel4.setText("Hepatities B Vaccine cost must be greater than 20$");
        }else{
            hepBErrorLabel4.setText("");
        }
    }//GEN-LAST:event_txtFieldHptBVaccineFocusLost

    private void txtFieldHPVFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldHPVFocusLost
        // TODO add your handling code here:
        if(txtFieldHPV.getText().isEmpty()){
            hpvVaccineError = true;
        }
        else{
            double cost;
            try{
                cost = Double.parseDouble(txtFieldHPV.getText());
            }catch(NumberFormatException e){
                hpvVaccineError = true;
                JOptionPane.showMessageDialog(null, "Please enter a valid float value for cost");
                return;
            }
            if (cost < 20){
                hpvVaccineError = true;
            }else{
                hpvVaccineError = false;
            }
        }
        
        
        if(hpvVaccineError){
            hpvErrorLAbel4.setText("HPV Vaccine cost must be greater than 20$");
        }else{
            hpvErrorLAbel4.setText("");
        }
    }//GEN-LAST:event_txtFieldHPVFocusLost

    private void txtFieldIPVFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldIPVFocusLost
        // TODO add your handling code here:
        if(txtFieldIPV.getText().isEmpty()){
            ipvVaccineError = true;
        }
        else{
            double cost;
            try{
                cost = Double.parseDouble(txtFieldIPV.getText());
            }catch(NumberFormatException e){
                ipvVaccineError = true;
                JOptionPane.showMessageDialog(null, "Please enter a valid float value for cost");
                return;
            }
            if (cost < 20){
                ipvVaccineError = true;
            }else{
                ipvVaccineError = false;
            }
        }
        
        
        if(ipvVaccineError){
            ipvErrorLabel4.setText("IPV Vaccine cost must be greater than 20$");
        }else{
            ipvErrorLabel4.setText("");
        }
    }//GEN-LAST:event_txtFieldIPVFocusLost

    private void txtFieldMMRFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldMMRFocusLost
        // TODO add your handling code here:
        if(txtFieldMMR.getText().isEmpty()){
            mmRVaccineError = true;
        }
        else{
            double cost;
            try{
                cost = Double.parseDouble(txtFieldMMR.getText());
            }catch(NumberFormatException e){
                mmRVaccineError = true;
                JOptionPane.showMessageDialog(null, "Please enter a valid float value for cost");
                return;
            }
            if (cost < 20){
                mmRVaccineError = true;
            }else{
                mmRVaccineError = false;
            }
        }
        
        
        if(mmRVaccineError){
            mmrErrorLabel4.setText("MMR Vaccine cost must be greater than 20$");
        }else{
            mmrErrorLabel4.setText("");
        }
    }//GEN-LAST:event_txtFieldMMRFocusLost

    private void txtFieldHrtSurgeryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldHrtSurgeryFocusLost
            // TODO add your handling code here:
            if(txtFieldHrtSurgery.getText().isEmpty()){
            byPassSurgeryError = true;
        }
        else{
            double cost;
            try{
                cost = Double.parseDouble(txtFieldHrtSurgery.getText());
            }catch(NumberFormatException e){
                byPassSurgeryError = true;
                JOptionPane.showMessageDialog(null, "Please enter a valid float value for cost");
                return;
            }
            if (cost < 100){
                byPassSurgeryError = true;
            }else{
                byPassSurgeryError = false;
            }
        }
        
        
        if(byPassSurgeryError){
            heartErrorLabel.setText("Heart Surgery cost must be greater than 100$");
        }else{
            heartErrorLabel.setText("");
        }
    }//GEN-LAST:event_txtFieldHrtSurgeryFocusLost

    private void txtFieldAngSurgeryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldAngSurgeryFocusLost
        // TODO add your handling code here:
        if(txtFieldAngSurgery.getText().isEmpty()){
            angioSugeryError = true;
        }
        else{
            double cost;
            try{
                cost = Double.parseDouble(txtFieldAngSurgery.getText());
            }catch(NumberFormatException e){
                angioSugeryError = true;
                JOptionPane.showMessageDialog(null, "Please enter a valid float value for cost");
                return;
            }
            if (cost < 100){
                angioSugeryError = true;
            }else{
                angioSugeryError = false;
            }
        }
        
        
        if(angioSugeryError){
            angioErrorLabel.setText("Angioplasty Surgery cost must be greater than 100$");
        }else{
            angioErrorLabel.setText("");
        }
    }//GEN-LAST:event_txtFieldAngSurgeryFocusLost

    private void txtFieldKRsurgeryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldKRsurgeryFocusLost
        // TODO add your handling code here:
        if(txtFieldKRsurgery.getText().isEmpty()){
            kneeSurgeryError = true;
        }
        else{
            double cost;
            try{
                cost = Double.parseDouble(txtFieldKRsurgery.getText());
            }catch(NumberFormatException e){
                kneeSurgeryError = true;
                JOptionPane.showMessageDialog(null, "Please enter a valid float value for cost");
                return;
            }
            if (cost < 100){
                kneeSurgeryError = true;
            }else{
                kneeSurgeryError = false;
            }
        }
        
        
        if(kneeSurgeryError){
            kneeErrorLAbel.setText("Knee Replacement Surgery cost must be greater than 100$");
        }else{
            kneeErrorLAbel.setText("");
        }
    }//GEN-LAST:event_txtFieldKRsurgeryFocusLost

    private void txtFieldCorneaSurgeryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldCorneaSurgeryFocusLost
        // TODO add your handling code here:
        if(txtFieldCorneaSurgery.getText().isEmpty()){
            corneaSugeryError = true;
        }
        else{
            double cost;
            try{
                cost = Double.parseDouble(txtFieldCorneaSurgery.getText());
            }catch(NumberFormatException e){
                corneaSugeryError = true;
                JOptionPane.showMessageDialog(null, "Please enter a valid float value for cost");
                return;
            }
            if (cost < 100){
                corneaSugeryError = true;
            }else{
                corneaSugeryError = false;
            }
        }
        
        
        if(corneaSugeryError){
            corneaErrorLabel.setText("Cornea Surgery cost must be greater than 100$");
        }else{
            corneaErrorLabel.setText("");
        }
    }//GEN-LAST:event_txtFieldCorneaSurgeryFocusLost

    private void txtFieldMRIcostFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldMRIcostFocusLost
        // TODO add your handling code here:
        if(txtFieldMRIcost.getText().isEmpty()){
            mriScanError = true;
        }
        else{
            double cost;
            try{
                cost = Double.parseDouble(txtFieldMRIcost.getText());
            }catch(NumberFormatException e){
                mriScanError = true;
                JOptionPane.showMessageDialog(null, "Please enter a valid float value for cost");
                return;
            }
            if (cost < 50){
                mriScanError = true;
            }else{
                mriScanError = false;
            }
        }
        
        
        if(mriScanError){
            MRIErrorLabel.setText("MRI Scan cost must be greater than 50$");
        }else{
            MRIErrorLabel.setText("");
        }
    }//GEN-LAST:event_txtFieldMRIcostFocusLost

    private void txtFieldEEGcostFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldEEGcostFocusLost
        // TODO add your handling code here:
        if(txtFieldEEGcost.getText().isEmpty()){
            eegError = true;
        }
        else{
            double cost;
            try{
                cost = Double.parseDouble(txtFieldEEGcost.getText());
            }catch(NumberFormatException e){
                eegError = true;
                JOptionPane.showMessageDialog(null, "Please enter a valid float value for cost");
                return;
            }
            if (cost < 50){
                eegError = true;
            }else{
                eegError = false;
            }
        }
        
        
        if(eegError){
            EEGErrorLabel.setText("EEG cost must be greater than 50$");
        }else{
            EEGErrorLabel.setText("");
        }
    }//GEN-LAST:event_txtFieldEEGcostFocusLost

    private void txtFieldECGcostFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldECGcostFocusLost
        // TODO add your handling code here:
        if(txtFieldECGcost.getText().isEmpty()){
            ecgError = true;
        }
        else{
            double cost;
            try{
                cost = Double.parseDouble(txtFieldECGcost.getText());
            }catch(NumberFormatException e){
                ecgError = true;
                JOptionPane.showMessageDialog(null, "Please enter a valid float value for cost");
                return;
            }
            if (cost < 50){
                ecgError = true;
            }else{
                ecgError = false;
            }
        }
        
        
        if(ecgError){
            ECGErrorLabel.setText("ECG cost must be greater than 50$");
        }else{
            ECGErrorLabel.setText("");
        }
    }//GEN-LAST:event_txtFieldECGcostFocusLost

    private void txtFieldXRaycostFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldXRaycostFocusLost
        // TODO add your handling code here:
        if(txtFieldXRaycost.getText().isEmpty()){
            xrayError = true;
        }
        else{
            double cost;
            try{
                cost = Double.parseDouble(txtFieldXRaycost.getText());
            }catch(NumberFormatException e){
                xrayError = true;
                JOptionPane.showMessageDialog(null, "Please enter a valid float value for cost");
                return;
            }
            if (cost < 50){
                xrayError = true;
            }else{
                xrayError = false;
            }
        }
        
        
        if(xrayError){
            xrayErrorLabel.setText("X-Ray cost must be greater than 50$");
        }else{
            xrayErrorLabel.setText("");
        }
    }//GEN-LAST:event_txtFieldXRaycostFocusLost

    private void txtFieldConsultationFeeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldConsultationFeeFocusLost
        // TODO add your handling code here:
         if(txtFieldConsultationFee.getText().isEmpty()){
            consultationError = true;
        }
        else{
            double cost;
            try{
                cost = Double.parseDouble(txtFieldConsultationFee.getText());
            }catch(NumberFormatException e){
                consultationError = true;
                JOptionPane.showMessageDialog(null, "Please enter a valid float value for cost");
                return;
            }
            if (cost < 20){
                consultationError = true;
            }else{
                consultationError = false;
            }
        }
        
        
        if(consultationError){
            consultationErrorLabel.setText("Consultation Fee must be greater than 20$");
        }else{
            consultationErrorLabel.setText("");
        }
    }//GEN-LAST:event_txtFieldConsultationFeeFocusLost

    private void txtFieldCorneaSurgeryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldCorneaSurgeryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldCorneaSurgeryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ECGErrorLabel;
    private javax.swing.JLabel EEGErrorLabel;
    private javax.swing.JLabel LocationNameLabel;
    private javax.swing.JLabel MRIErrorLabel;
    private javax.swing.JLabel angioErrorLabel;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel consultationErrorLabel;
    private javax.swing.JLabel corneaErrorLabel;
    private javax.swing.JLabel fluErrorLabel4;
    private javax.swing.JLabel heartErrorLabel;
    private javax.swing.JLabel hepAErrorLabel4;
    private javax.swing.JLabel hepBErrorLabel4;
    private javax.swing.JLabel hospitalNameLabel;
    private javax.swing.JLabel hpvErrorLAbel4;
    private javax.swing.JLabel ipvErrorLabel4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JLabel kneeErrorLAbel;
    private javax.swing.JLabel mmrErrorLabel4;
    private javax.swing.JTextField txtFieldAngSurgery;
    private javax.swing.JTextField txtFieldConsultationFee;
    private javax.swing.JTextField txtFieldCorneaSurgery;
    private javax.swing.JTextField txtFieldECGcost;
    private javax.swing.JTextField txtFieldEEGcost;
    private javax.swing.JTextField txtFieldFluVaccine;
    private javax.swing.JTextField txtFieldHPV;
    private javax.swing.JTextField txtFieldHptAVaccine;
    private javax.swing.JTextField txtFieldHptBVaccine;
    private javax.swing.JTextField txtFieldHrtSurgery;
    private javax.swing.JTextField txtFieldIPV;
    private javax.swing.JTextField txtFieldKRsurgery;
    private javax.swing.JTextField txtFieldMMR;
    private javax.swing.JTextField txtFieldMRIcost;
    private javax.swing.JTextField txtFieldXRaycost;
    private javax.swing.JButton updateBtn;
    private javax.swing.JLabel xrayErrorLabel;
    // End of variables declaration//GEN-END:variables
}
